# View (Reshape)
### dim 모든 곱 항상 같아야함 size([x, y, z])

In [1]:
import numpy as np
import torch

In [4]:
t = np.array = ([[[0, 1, 2],
                 [3, 4, 5]],
                 
                 [[6, 7, 8],
                 [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [5]:
print(ft.view([-1, 3]))
            # 앞엔모르겠고, 뒤는 3
print(ft.view([-1, 3]).shape)
            # rowxcol, 3

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [7]:
print(ft.view([-1, 1, 3]))
            #    dim[1]
print(ft.view([-1, 1, 3]).shape) 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


주어진 정보에 따르면, 이 텐서의 크기(`torch.Size([4, 1, 3])`)는 `(4, 1, 3)`으로 표현되며, 이것은 3차원 텐서입니다.

텐서의 각 차원에 대한 설명은 다음과 같습니다:

1. 첫 번째 차원(1번째 값): 크기 4
   - 이 차원은 텐서의 가장 바깥쪽 차원으로, 4개의 원소를 가지고 있습니다. 이 차원은 주로 "배치(batch)"라고 불리며, 여러 데이터 샘플을 동시에 처리하는 데 사용될 수 있습니다.

2. 두 번째 차원(2번째 값 -> 큰 묶음으로 보면 될 듯): 크기 1
   - 이 차원은 1개의 원소만 가지고 있으므로 길이가 1인 차원입니다. 이러한 차원은 주로 "채널(channel)" 차원이라고 불리며, 이미지 처리와 관련하여 사용될 수3.습니다.

3. 세 번째 차원(3번째 값): 크기 3
   - 이 차원은 3개의 원소를 가지고 있으며, 각각의 원소는 실수값을 나타냅니다. 이 차원은 주로 데이터의 특성(feature)을 나타내며, 예를 들어 하나의 데이터 포인트가 3개의 특성을 가진 경우에 사용될 수 있습니다.

따라서 주어진 텐서는 4개의 데이터 배치(batch)가 있고, 각 데이터는 1개의 채널(channel)을 가지며, 각 채널은 3개의 특성(feature)을 가지고 있습니다. 이러한 3차원 텐서는 딥러닝과 같은 다양한 분야에서 데이터의 표현과 처리에 사용됩니다.

# Squeez

In [9]:
ft = torch.FloatTensor([[0], [1], [2]])  // col 1개 = element 1개 = dim 1 -> 날려버림 (3, )
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.squeeze()) 
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


`squeeze` 함수는 PyTorch에서 사용되는 함수 중 하나로, 텐서(tensor)의 차원 중 크기가 1인 차원을 제거하는 데 사용됩니다. 이 함수는 텐서의 모양(shape)을 변경하고, 데이터에는 영향을 주지 않으면서 차원을 조정합니다.

`squeeze` 함수는 다음과 같이 사용됩니다:

```python
torch.squeeze(input, dim=None)
```

- `input`: 크기가 1인 차원을 제거할 입력 텐서입니다.
- `dim` (선택 사항): 제거할 차원을 지정하는 매개변수입니다. 이 매개변수를 지정하지 않으면 모든 크기가 1인 차원이 제거됩니다.

`squeeze` 함수는 다음과 같이 작동합니다:

1. 크기가 1인 차원을 찾습니다. 이러한 차원은 제거 대상이 됩니다.
2. `dim` 매개변수가 제공되면 해당 차원만 제거하고, `dim`이 제공되지 않으면 모든 크기가 1인 차원을 제거합니다.
3. 결과로 나오는 텐서의 모양(shape)이 변경되며, 크기가 1인 차원은 모두 제거됩니다.
4. 데이터는 변경되지 않고 그대로 유지됩니다.

예를 들어, 다음과 같이 크기가 1인 차원을 제거하는 예를 살펴보겠습니다:

```python
import torch

# 크기가 1인 차원이 있는 텐서
t = torch.randn(1, 3, 1, 2)  # 크기가 1인 차원이 2개 존재

# squeeze를 사용하여 크기가 1인 차원 제거
result = torch.squeeze(t)

print(t.shape)       # torch.Size([1, 3, 1, 2])
print(result.shape)  # torch.Size([3, 2])
```

위의 예제에서 `squeeze` 함수를 사용하여 크기가 1인 차원을 제거하면 결과 텐서의 모양이 변경되어 `(3, 2)`가 됩니다.

# Unsqueeze

In [14]:
ft = torch.FloatTensor([0, 1, 2]) # dim 1 (3, )
print(ft.unsqueeze(0)) # dim[0]에 차원 1을 추가 (1, 3)

tensor([[0., 1., 2.]])


In [17]:
print(ft.view(1, -1))
        # 앞에 1

tensor([[0., 1., 2.]])


In [18]:
print(ft.unsqueeze(1))

tensor([[0.],
        [1.],
        [2.]])


In [19]:
print(ft.view(-1, 1))

tensor([[0.],
        [1.],
        [2.]])


# Type Casting
- Long/Byte Tensor

In [26]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
# print(lt.mean()) 불가

tensor([1, 2, 3, 4])


In [27]:
print(lt.float())
print(lt.float().mean())

tensor([1., 2., 3., 4.])
tensor(2.5000)


In [28]:
# 마스킹 값으로 활용
bt = torch.ByteTensor([True, False, True, True])  # Boolean 값            
print(bt)

tensor([1, 0, 1, 1], dtype=torch.uint8)


In [29]:
print(bt.long())  # 정수값

tensor([1, 0, 1, 1])


In [30]:
print(bt.float())

tensor([1., 0., 1., 1.])


# Concatenate 이어붙임

In [53]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [33]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking (list, dim)

In [34]:
x = torch.FloatTensor([1, 4])   # dim 1
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [42]:
print(torch.stack([x, y, z]))  # dim 2
                # 위로 쌓기
print(torch.stack([x, y, z], dim=1))
                            # 가로, 옆으로 쌓기 == Transpose해서

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [44]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))
                # dim 2

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Ones and Zeros() 함수
: shape은 같고 0 or 1 할당

In [45]:
x = torch.FloatTensor([[1, 2, 3], [3, 4, 5]])
print(x)

tensor([[1., 2., 3.],
        [3., 4., 5.]])


In [46]:
print(torch.ones_like(x))    # 같은 device에 선언됨
print(torch.zeros_like(x))   # multiple gpu, 동일 장치에서 연산해야함

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-Place Operation : mul(), mul_()

In [51]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [52]:
print(x.mul(2.))  # multi 2
print(x)
print(x.mul_(2.)) # 메모리 따로 선언안하고도 연산 수행, 값 바꿈
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
