In [7]:
pip cache purge  

Files removed: 4
Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 1.4 MB/s eta 0:00:0000:0100:02
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/5e/5d/97afbafd9d584ff1b45fcb354a479a3609bd97f912f8f1f6c563cb1fae21/filelock-3.12.4-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 9.9 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 8.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 9.6 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 3.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 3.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 4.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 10.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 3.6 MB/s et

In [9]:
import numpy as np
import torch

# 1d array with numpy
# 2d array(matix) with numpy
# 1d array with pytorch tensor
# 2d array with pytorch tensor  
 ### : shape, sizeof()

In [11]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [12]:
print(t.dim())
print(t.size())

2
torch.Size([3, 3])


In [17]:
print(t[:, 2]) # 모든 row들 중에 (2 + 1)번째 col

tensor([3., 6., 9.])


In [18]:
print(t[1, 2])  # (1 + 1)번째 row 중에 (2 + 1) 번째 col

tensor(6.)


# BroadCasting
: 행렬 곱/합 rule에 맞지 않아도 auto casting해줌

In [20]:
# vector + scalar
m1 = torch.FloatTensor([[1, 1]])
m2 = torch.FloatTensor([2])    # (1차원) [2] -> [[2, 2]]
print(m1 + m2)

tensor([[3., 3.]])


In [22]:
# (2x1) + (1x2) 
m3 = torch.FloatTensor([[2, 2]])  # -> (2, 2)
m4 = torch.FloatTensor([[3], [4]]) # -> (2, 2)   
print(m3 + m4)   # (2, 2) + (2, 2)

tensor([[5., 5.],
        [6., 6.]])


# Multiplication vs Matrix Multiplication

### BroadCasting : element-wise-multiplication

In [29]:
# (1x2) * (2x1)
m5 = torch.FloatTensor([[2, 2]])  # 1x2
m6 = torch.FloatTensor([[3], [4]])  # 2x1
print(m5 * m6, '\n')  # 원래는 (1, 1) - 행렬곱에서

tensor([[6., 6.],
        [8., 8.]]) 



In [30]:
# (2x1) * (1x2)
print(m5 * m4, '\n')

tensor([[4., 4.]]) 



### Matrix Multiplication

In [31]:
print(m5.matmul(m6), '\n') 
print(m6.matmul(m5), '\n')

tensor([[14.]]) 

tensor([[6., 6.],
        [8., 8.]]) 



# Mean

In [34]:
t = torch.FloatTensor([1,2])  # 1차원 (괄호 하나)
print(t.mean())

tensor(1.5000)


In [35]:
t = torch.LongTensor([1,2])
print(t.mean())

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

이 오류는 PyTorch에서 `mean()` 함수를 호출할 때 발생한 것으로, 오류 메시지에서 알 수 있듯이 `mean()` 함수는 부동 소수점 또는 복소수 데이터 타입에 대해서만 동작합니다. 따라서 `torch.LongTensor`와 같은 **정수 데이터 타입** 에 대해서는 `mean()` 함수를 직접 호출할 수 없습니다.

해결 방법 중 하나는 입력 Tensor를 부동 소수점 데이터 타입으로 변환한 후 `mean()` 함수를 호출하는 것입니다. 예를 들어 `torch.FloatTensor`로 변환한 후 `mean()`을 호출할 수 있습니다:

```python
t = torch.LongTensor([1, 2]).float()  # 정수 Tensor를 부동 소수점 Tensor로 변환
print(t.mean())
```

또는 생성 시에 바로 부동 소수점 데이터 타입을 사용하도록 Tensor를 생성할 수도 있습니다:

```python
t = torch.FloatTensor([1, 2])
print(t.mean())
```

이렇게 하면 오류가 발생하지 않고 Tensor의 평균을 계산할 수 있습니다.

In [38]:
m = torch.FloatTensor([[1, 2], [3, 4]])
print(m.mean())  # 4개 elemens의 mean

tensor(2.5000)


In [42]:
print(m.mean(dim=0))  # 각 col(첫번째차원) 에 대한 평균
print(m.mean(dim=1))  # 각 row(두번째차원) 에 대한 평균
print(m.mean(dim=-1))  # 마찬가지로 row

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [53]:
t = torch.FloatTensor([[1, 4], [2, 3]])
print(t.sum())  # 전체 elements 합

tensor(10.)


In [54]:
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([3., 7.])
tensor([5., 5.])
tensor([5., 5.])


# Max and Argmax

In [57]:
print(t.max())  # return nur eins

tensor(4.)


### 그런데 dim을 specify하면 2 values도 return 가능함
#### max 값 & argmax(=index) 값

In [61]:
t = torch.FloatTensor([[1, 4], [2, 3]])
print(t.max(dim=0))  # col 기준

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 0]))


In [63]:
print(t.max(dim=0)[0])  // 위 결과값(t.max(dim=0))은 배열
                        // t.max(dim=0)[0]은 value
print(t.max(dim=0)[1])  // t.max(dim=0)[1]은 index, argmax

tensor([2., 4.])
tensor([1, 0])
